function resource=ehr_exporter(result,patientId)
%EHR_EXPORTER Create a FHIR Observation-compatible MATLAB struct.
resource=struct('resourceType','Observation','status','final','subject',struct('reference',['Patient/' char(patientId)]), ...
 'code',struct('coding',struct('system','http://loinc.org','code','71490-7','display','Diabetic retinopathy assessment')), ...
 'valueCodeableConcept',struct('text',result.grading.label),'component',struct('code',struct('text','Referable DR'), ...
 'valueBoolean',result.grading.referable),'confidence',result.grading.confidence);
end
